### ISSUE TITLE
Update config.php

### ISSUE THREAD

**Issue by Draakoor** [kveldscholten/kvticket#3]
public function getInstallSql()
    {
        return 'CREATE TABLE IF NOT EXISTS `[prefix]_kvticket` (
                `id` INT(11) NOT NULL AUTO_INCREMENT,
                `title` VARCHAR(255) NOT NULL,
                `text` MEDIUMTEXT NOT NULL,
                `status` INT(11) NOT NULL DEFAULT 0,
                `editor` INT(11) NOT NULL DEFAULT 0,
                `creator` INT(11) NOT NULL DEFAULT 0,
                `cat` INT(11) NOT NULL DEFAULT 0,
                `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
                `updated_at` TIMESTAMP NOT NULL DEFAULT TIMESTAMP(),
                PRIMARY KEY (id)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=1;

            CREATE TABLE IF NOT EXISTS `[prefix]_kvticket_cat` (
                `id` INT(11) NOT NULL AUTO_INCREMENT,
                `title` VARCHAR(255) NOT NULL,
                PRIMARY KEY (`id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=1;';
    }

This Code is outdated pls update :)

**Comment by kveldscholten** [comment]
Teste es mal hiermit https://github.com/kveldscholten/kvticket/commit/32c43299e9d29f12157fb13f26b96bc40afdd92e 
Welche MySQL Version nutzt dein Server? Es kann sein das die Funktion erst mit MySQL 5.6.5 läuft
